import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from "../app/components/home-page/navbar/index";
import Home from "../app/components/home-page/home";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <Home/>
    </div>
  )
}

export default HomePage
