import type {NextPage} from 'next'
import Head from 'next/head'
import {useEffect, useState} from "react";

import Navbar from "../app/components/home-page/navbar/index";
import Home from "../app/components/home-page/home";
import callApi from "../app/helpers/callApi";
import About from "../app/components/home-page/about";
import Services from "../app/components/home-page/services";
import Experience from "../app/components/home-page/experience";
import ClientsReviews from "../app/components/home-page/clientsReviews";
import Contact from "../app/components/home-page/contact";
import Footer from "../app/components/home-page/footer";
import Preloader from "../app/components/home-page/preloader";
import Blog from "../app/components/home-page/blog";
import axios from "axios";

const HomePage: NextPage = () => {

    const [information, setInformation] = useState()
    const [loading, setLoading] = useState<boolean>(false)

    useEffect(() => {
        callApi().get('information').then(res => {
            setInformation(res?.data?.data);
            setLoading(false)
        })
    }, [])

    return (
        <>
            {
                loading ? <Preloader/>
                    :
                    <div>
                        <Head>
                            <title>Create Next App</title>
                            <meta name="description" content="Generated by create next app"/>
                            <link rel="icon" href="/favicon.ico"/>
                        </Head>
                        <Navbar/>
                        <Home data={information}/>
                        <About data={information}/>
                        <Services/>
                        <Experience/>
                        <ClientsReviews/>
                        <Blog/>
                        <Contact data={information}/>
                        <Footer/>
                    </div>
            }
        </>

    )
}



export default HomePage

