import type { NextPage } from 'next'
import Head from 'next/head'
import {useEffect, useState} from "react";

import Navbar from "../app/components/home-page/navbar/index";
import Home from "../app/components/home-page/home";
import callApi from "../app/helpers/callApi";
import About from "../app/components/home-page/about";
import Services from "../app/components/home-page/services";
import Experience from "../app/components/home-page/experience";

const HomePage: NextPage = () => {

    const [information , setInformation] = useState()

    useEffect(()=>{
        callApi().get('information').then(res => setInformation(res?.data?.data))
    },[])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <Home data={information}/>
        <About data={information}/>
        <Services/>
        <Experience/>
    </div>
  )
}

export default HomePage
